coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        target: 80%
        threshold: 2%
        if_ci_failed: error
    
    patch:
      default:
        target: 75%
        threshold: 5%
        if_ci_failed: error

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

ignore:
  - "tests/**"
  - "**/__pycache__/**"
  - "**/conftest.py"
  - "setup.py"
  - "**/__main__.py"
